// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitOfWorkDesignPattern.Data.Contexts;

namespace UnitOfWorkDesignPattern.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UnitOfWorkDesignPattern.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2019, 10, 1, 13, 55, 33, 673, DateTimeKind.Utc).AddTicks(3937),
                            EMail = "e.dedeoglu@gmail.com",
                            Name = "Erçin",
                            Password = "1q2w3e4r",
                            Surname = "Dedeoğlu",
                            Username = "Phantasm"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2019, 10, 1, 13, 55, 33, 673, DateTimeKind.Utc).AddTicks(7989),
                            EMail = "ata.dedeoglu@unknown.com",
                            Name = "Ata",
                            Password = "123456",
                            Surname = "Dedeoğlu",
                            Username = "Atiş"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2019, 10, 1, 13, 55, 33, 673, DateTimeKind.Utc).AddTicks(8139),
                            EMail = "dedeco@yahoo.com",
                            Name = "İmdat Ercan",
                            Password = "1234",
                            Surname = "Dedeoğlu",
                            Username = "Eco"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2019, 10, 1, 13, 55, 33, 673, DateTimeKind.Utc).AddTicks(8152),
                            EMail = "yusuf.dedeoglu@unknown.com",
                            Name = "Yusuf",
                            Password = "654321",
                            Surname = "Dedeoğlu",
                            Username = "Dedeler"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
